# Generated by Django 4.1.7 on 2023-05-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_nais', models.DateTimeField()),
                ('ville', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('mdp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pfa_api.personne')),
                ('entreprise', models.CharField(max_length=180)),
                ('black_list', models.BooleanField(default=False)),
            ],
            bases=('pfa_api.personne',),
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_experience', models.IntegerField(max_length=100)),
                ('connaissance', models.CharField(max_length=100)),
                ('contrat', models.CharField(max_length=100)),
                ('critere', models.CharField(max_length=100)),
                ('formation', models.CharField(max_length=100)),
                ('mission', models.CharField(max_length=100)),
                ('nbr_a_recruter', models.IntegerField(max_length=100)),
                ('salaire', models.FloatField(max_length=100)),
                ('tache_principale', models.CharField(max_length=100)),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa_api.langue')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa_api.specialite')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa_api.ville')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa_api.recruteur')),
            ],
        ),
    ]
